spring:
  application:
    name: assinatura-rsa

  security:
    user:
      name: admin
      password: admin

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:


api:
  security:
    token:
      secret: my-secret-key-from-video
